In [1]:
import pandas as pd
import numpy as np

In [2]:
scores_df = pd.read_csv('2023-gwdata-bootcamp-all-scores-2024-01-06T16:50:15.csv')
scores_df.head()

,DateSubmitted,SubmissionId,TeamId,UserName,TeamName,IsSelected,PublicScore,PrivateScore,UserEmail
0,2023-12-29 14:02:00,35654256,11473407,wtl777,Qinglin Yan,False,0.493854,0.493854,[private]
1,2023-12-29 14:36:52,35654835,11473407,wtl777,Qinglin Yan,False,0.784320,0.784320,[private]
2,2023-12-29 14:43:53,35654948,11471765,liuran06,1500！！！,False,0.800756,0.800756,[private]
3,2023-12-29 14:55:41,35655105,11473407,wtl777,Qinglin Yan,False,0.781739,0.781739,[private]
4,2023-12-29 15:31:24,35655685,11459225,paarthurnaxx,XAO,False,0.780511,0.780511,[private]

In [3]:
scores_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692 entries, 0 to 691
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DateSubmitted  692 non-null    object
 1   SubmissionId   692 non-null    int64
 2   TeamId         692 non-null    int64
 3   UserName       692 non-null    object
 4   TeamName       692 non-null    object
 5   IsSelected     692 non-null    bool
 6   PublicScore    692 non-null    float64
 7   PrivateScore   692 non-null    float64
 8   UserEmail      692 non-null    object
dtypes: bool(1), float64(2), int64(2), object(4)
memory usage: 44.1+ KB

In [4]:
scores_df['DateSubmitted']

0      2023-12-29 14:02:00
1      2023-12-29 14:36:52
2      2023-12-29 14:43:53
3      2023-12-29 14:55:41
4      2023-12-29 15:31:24
              ...
687    2024-01-06 15:56:45
688    2024-01-06 15:57:30
689    2024-01-06 15:57:36
690    2024-01-06 15:58:19
691    2024-01-06 15:58:20
Name: DateSubmitted, Length: 692, dtype: object

In [5]:
pd.to_datetime(scores_df['DateSubmitted']).dt.tz_localize('Asia/Shanghai')

0     2023-12-29 14:02:00+08:00
1     2023-12-29 14:36:52+08:00
2     2023-12-29 14:43:53+08:00
3     2023-12-29 14:55:41+08:00
4     2023-12-29 15:31:24+08:00
                 ...
687   2024-01-06 15:56:45+08:00
688   2024-01-06 15:57:30+08:00
689   2024-01-06 15:57:36+08:00
690   2024-01-06 15:58:19+08:00
691   2024-01-06 15:58:20+08:00
Name: DateSubmitted, Length: 692, dtype: datetime64[ns, Asia/Shanghai]

In [6]:
from datetime import datetime

# 将 DateSubmitted 列转换为 datetime，并对时间进行取整到小时
scores_df['DateSubmitted'] = pd.to_datetime(scores_df['DateSubmitted']).dt.tz_localize('utc').dt.tz_convert('Asia/Shanghai')

# 创建一个新的 DataFrame，其中包含每个团队在每个小时的最高分数
# 首先对数据进行分组
grouped_scores = scores_df.groupby(['TeamId', 'TeamName', 'DateSubmitted'])

# 对每个团队和时间段，选取 PublicScore 的最大值
max_scores = grouped_scores['PublicScore'].max().reset_index()

# 重新组织 DataFrame，将时间作为列，团队作为行
pivot_scores = max_scores.pivot(index=['TeamId', 'TeamName'], columns='DateSubmitted', values='PublicScore')

In [7]:
pivot_scores.head()

,DateSubmitted,2023-12-29 22:02:00+08:00,2023-12-29 22:36:52+08:00,2023-12-29 22:43:53+08:00,2023-12-29 22:55:41+08:00,2023-12-29 23:31:24+08:00,2023-12-30 00:30:28+08:00,2023-12-30 09:21:48+08:00,2023-12-30 14:37:43+08:00,2023-12-30 16:01:19+08:00,2023-12-30 17:05:45+08:00,...,2024-01-06 23:53:20+08:00,2024-01-06 23:54:29+08:00,2024-01-06 23:54:46+08:00,2024-01-06 23:55:47+08:00,2024-01-06 23:56:15+08:00,2024-01-06 23:56:45+08:00,2024-01-06 23:57:30+08:00,2024-01-06 23:57:36+08:00,2024-01-06 23:58:19+08:00,2024-01-06 23:58:20+08:00
TeamId,TeamName,,,,,,,,,,,,,,,,,,,,,
11452837,Yinda Guo,NaN,NaN,NaN,NaN,NaN,0.812989,NaN,NaN,NaN,0.500845,...,NaN,NaN,NaN,NaN,0.848929,NaN,NaN,0.850712,NaN,NaN
11457574,Zhao_Hao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.803771,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11458502,MengXiaofeng-UCAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11458822,jingzou23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11459225,XAO,NaN,NaN,NaN,NaN,0.780511,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
def fill_nan_with_max(arr):
    # 初始化最大值为0，因为如果序列开始就是nan，需要用0填充
    max_val = 0
    # 遍历数组中的每个元素
    for i in range(len(arr)):
        if np.isnan(arr[i]):
            # 如果元素是nan，则用当前的最大值替换
            arr[i] = max_val
        else:
            # 更新最大值
            max_val = max(max_val, arr[i])
    return arr

# 示例数组
arr = np.array([np.nan, 3, np.nan, 2, np.nan, 5, np.nan])

# 调用函数并打印结果
fill_nan_with_max(arr)

array([0., 3., 3., 2., 3., 5., 5.])

In [9]:
pivot_scores_T = pivot_scores.T
for col in pivot_scores_T:
    pivot_scores_T.loc[:,col] = fill_nan_with_max(pivot_scores_T[col].values)

In [10]:
pivot_scores = pivot_scores_T.T

In [11]:
# 显示转换后的 DataFrame 的前几行
pivot_scores.head()

,DateSubmitted,2023-12-29 22:02:00+08:00,2023-12-29 22:36:52+08:00,2023-12-29 22:43:53+08:00,2023-12-29 22:55:41+08:00,2023-12-29 23:31:24+08:00,2023-12-30 00:30:28+08:00,2023-12-30 09:21:48+08:00,2023-12-30 14:37:43+08:00,2023-12-30 16:01:19+08:00,2023-12-30 17:05:45+08:00,...,2024-01-06 23:53:20+08:00,2024-01-06 23:54:29+08:00,2024-01-06 23:54:46+08:00,2024-01-06 23:55:47+08:00,2024-01-06 23:56:15+08:00,2024-01-06 23:56:45+08:00,2024-01-06 23:57:30+08:00,2024-01-06 23:57:36+08:00,2024-01-06 23:58:19+08:00,2024-01-06 23:58:20+08:00
TeamId,TeamName,,,,,,,,,,,,,,,,,,,,,
11452837,Yinda Guo,0.0,0.0,0.0,0.0,0.000000,0.812989,0.812989,0.812989,0.812989,0.500845,...,0.858325,0.858325,0.858325,0.858325,0.848929,0.858325,0.858325,0.850712,0.858325,0.858325
11457574,Zhao_Hao,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.803771,0.820479,0.820479,0.820479,0.820479,0.820479,0.820479,0.820479,0.820479,0.820479
11458502,MengXiaofeng-UCAS,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.851885,0.851885,0.851885,0.851885,0.851885,0.851885,0.851885,0.851885,0.851885,0.851885
11458822,jingzou23,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.791182,0.791182,0.791182,0.791182,0.791182,0.791182,0.791182,0.791182,0.791182,0.791182
11459225,XAO,0.0,0.0,0.0,0.0,0.780511,0.780511,0.780511,0.780511,0.780511,0.780511,...,0.861731,0.861731,0.861731,0.861731,0.861731,0.861731,0.861731,0.861731,0.861731,0.861731

In [12]:
pivot_scores.to_csv('plot.csv')